### ISSUE TITLE
Loader is in incorrect folder

### ISSUE THREAD

**Issue by Skidrow68** [SkyrimTogether/issues-launcher#1]
## Description

When o press on start i only get up Error: Loader is in incorrect folder, is that becase i need to install Skyrim together in same folder as skyrim is or is it simple for i use Skyrim SE VR?

![together](https://user-images.githubusercontent.com/19759240/51756044-64e43d80-20c0-11e9-8ed0-69057f274052.jpg)

**Comment by Ueine** [comment]
Of course it wouldn't launch, its not the same game.

**Comment by Skidrow68** [comment]
It is the same game what they change is controller information otherwis you couldnt load mods and so.

**Comment by Ueine** [comment]
its a complete different location on regedit

**Comment by WopsS** [comment]
Our mod doesn't work with `Skyrim VR`, it needs some addresses that are present on `Special Edition` even if you get it to find `Skyrim VR` it will crash right away.
