### ISSUE TITLE
Skyrim Cell host makes duplicate NPC's

### ISSUE THREAD

**Issue by ButtonSmasher** [SkyrimTogether/issues-launcher#10]
## Description

Playing with a new buddy of mine and we decided to travel to riften, at the time i wasn't the cellhost of ''Skyrim'' so we travelled with the cart system and we went to riften. I talked to the guy on the cart and i went on. 

He then tried to talking to him what worked, but once he got on the game didn't do a thing. He just sat there. He tried over and over until he just decided to tp to me. I was just in conversation with the Guard at the gate so he could open up the gate for me. The moment he teleported to me a new set of guard spawned in right on the spot and not only guards but also other NPC's such as the stable master atleast for me. I went inside riften he told me he saw the duplicate guards and now even saw bandits just out of nowhere spawn in. When he said that he crashed and i went outside. No bandits, but still duplicate guards and a friendly draugr standing there with the guards.

## Steps to reproduce

How to reproduce this issue:

Non-cell host goes to a location by cart.
Cell-host tps if he cannot travel with cart.
Duplicate guards appear and bugs occur.

## Reproduction rate

We tried it twice on the same safe and both happend at the same time.

## Expected result

Be able to both travel with cart and not see duplicate guards/NPCs

## Your environment

* Launcher version: Latest version

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
    * Windows 10 x64

**Comment by Pokang** [comment]
This issueboard is for launcher-related issues.
Closing.
