### ISSUE TITLE
Server dll missing (libcrypto-1_1-x64.dll)

### ISSUE THREAD

**Issue by Xist3nce** [SkyrimTogether/issues-launcher#102]
The current version (1.0.6) of the launcher does not download the library (libcrypto-1_1-x64.dll) necessary to run a server with the server exe. Should be a quick fix to pop that back in.

**Comment by EduardoRosseti** [comment]
https://www.reddit.com/r/SkyrimTogether/comments/jqmciy/serverexe_system_error/

**Comment by Xist3nce** [comment]
Thanks for the heads up, might make a PR to see if they can roll it out into the next update.
