### ISSUE TITLE
Dropped Items disappearing

### ISSUE THREAD

**Issue by COLEY83** [SkyrimTogether/issues-launcher#11]
##Description

When dropping Weapons and armour (and likely orther items) they will ether fall through the world or just not drop at all. you can hear the sounds but nothing will apper to drop. this is happening while playing Solo but with ST loaded from Harbor.
I have no mods on just SKSE and ST (no not even the Unofficial Patch)

## Steps to reproduce

Relaunched game,
loaded save,
dropped items, it was still happening randomly 

## Reproduction rate

It apears to happon randomly with Weapons and Armour.
There is no signs to give away that it will or will not happen.

## Expected result
Be able to drop any items and then return at a alter time to retrive them.

## Your environment

* Launcher version: Latest

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

**Comment by Pokang** [comment]
This issueboard is for launcher-related issues.
Closing.
