### ISSUE TITLE
NPC conversations persisting in shops

### ISSUE THREAD

**Issue by COLEY83** [SkyrimTogether/issues-launcher#12]
## Description

While having a conversations a NPC and you request to see their wares, the shop opens yet you are unable to select the categories as they still invisibly have the conversation open and is you mouse click you can hear the other conversations options that they were able to give you and you have to press "ESC" to exit the conversation and continue to the shop. This also seems to disengage interaction with the NPC and they go on as normal "EG they walk about doing what they normally do" whiles the shop window is still active.
I have no mods on just SKSE and ST (no not even the Unofficial Patch)

## Steps to reproduce

Just load game, its always happening

## Reproduction rate

Its happening nearly all the time, may be odd NPCs working as normal but defiantly 99% of the time its bugged

## Expected result

NPC conversation should close and transition to shop without the need to press "ESC"

## Your environment

* Launcher version: Latest

* Game edition (choose on which edition do you have problems):

    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):

    * Windows 10 x64

## Evidence (optional)

Show us what happen.

**Comment by Dragonisser** [comment]
This has nothing to do with the launcher.

https://github.com/SkyrimTogether/issues-game

Also: 
https://github.com/SkyrimTogether/issues-game/issues/53
https://github.com/SkyrimTogether/issues-game/issues/104
https://github.com/SkyrimTogether/issues-game/issues/147
https://github.com/SkyrimTogether/issues-game/issues/214

**Comment by Pokang** [comment]
Wrong issues repository, and the issue has been reported countless times.
Closing.
