### ISSUE TITLE
endless "checking for updates" 

### ISSUE THREAD

**Issue by paul-verizer** [SkyrimTogether/issues-launcher#13]
so i just use the harbor launcher and it just seems like the checking for updates isn't progressing at all, i even left it on overnight just in case, as well as re launching as well as restating the computer, even as far as uninstalling and re installing.
     it seems to be consistent and keeps happening even tho im signed in and a patron member even on the launcher
 both the skyrim SE and harbor is on the same hard drive 
  it seems to launch the actual launcher its self but the moment i click install it just checks for updates

i run off of windows 10 x64
 
 my friend gets in the launcher no problem and he and i did all the same things for he is also running off of windows 10 x64

**Comment by Pokang** [comment]
Please reopen the issue with the template provided, removing everything from it really isn't going to get us anywhere, thank you.
