### ISSUE TITLE
crash up on connect

### ISSUE THREAD

**Issue by maestroi** [SkyrimTogether/issues-launcher#17]
## Description

see bellow what happens but this is on a freshly installed skyrim from steam, on 2 seprate windows 10 game computers.

it is on SKYRIM **not** SE version.

## Steps to reproduce

1. run skyrim
2. press right control
3. enter server address: 217.182.XXX.XXX ( a VPS running latest docker container)
4. it crashes game.

on server the message is 
```
root@vps397024:~# docker run -p 10578:10578/udp titledphoques/st-game-server
{"date":"2019-05-18 13:04:25,217", "level":"INFO", "event":"server_state", "value":"online", "port":10578 }
{"date":"2019-05-18 13:04:25,218", "level":"INFO", "event":"server_state", "value":"started", "token":"" }
{"date":"2019-05-18 13:05:28,115", "level":"INFO", "event":"connected", "connection_id":1 }
{"date":"2019-05-18 13:05:28,139", "level":"INFO", "event":"hello_received", "client_protocol":1903839940, "server_protocol":1903839940 }
{"date":"2019-05-18 13:05:28,143", "level":"INFO", "event":"hello", "connection_id":1, "name":"Faramir" }
{"date":"2019-05-18 13:05:34,744", "level":"ERROR", "event":"player_dtor_find_new_cell_host", "error":"npc_is_null" }
{"date":"2019-05-18 13:05:34,745", "level":"INFO", "event":"disconnected", "connection_id":1 }
{"date":"2019-05-18 13:12:06,844", "level":"INFO", "event":"connected", "connection_id":1 }
{"date":"2019-05-18 13:12:06,869", "level":"INFO", "event":"hello_received", "client_protocol":1903839940, "server_protocol":1903839940 }
{"date":"2019-05-18 13:12:06,946", "level":"INFO", "event":"hello", "connection_id":1, "name":"Minermanz" }
{"date":"2019-05-18 13:12:13,502", "level":"ERROR", "event":"player_dtor_find_new_cell_host", "error":"npc_is_null" }
{"date":"2019-05-18 13:12:13,503", "level":"INFO", "event":"disconnected", "connection_id":1 }
{"date":"2019-05-18 13:13:54,514", "level":"INFO", "event":"connected", "connection_id":1 }
{"date":"2019-05-18 13:13:54,541", "level":"INFO", "event":"hello_received", "client_protocol":1903839940, "server_protocol":1903839940 }
{"date":"2019-05-18 13:13:54,569", "level":"INFO", "event":"hello", "connection_id":1, "name":"Minermanz" }
{"date":"2019-05-18 13:14:01,112", "level":"ERROR", "event":"player_dtor_find_new_cell_host", "error":"npc_is_null" }
{"date":"2019-05-18 13:14:01,113", "level":"INFO", "event":"disconnected", "connection_id":1 }
```

How to reproduce this issue:

1. Start the launcher.
2. Connect login.
3. Fail to login.

## Reproduction rate

10 times

## Expected result

not crashing on connect

## Your environment

* Launcher version:

* Game edition (choose on which edition do you have problems):
    *** The Elder Scrolls V: Skyrim***
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
    * Windows 7 x32
    * Windows 7 x64
    * Windows 10 x32
    *** Windows 10 x64***

## Evidence (optional)

Show us what happen.

## Final checks for the reporter

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by Dumbeldor** [comment]
Hi,

thanks for your feedback. But you've got the wrong place, it's not a problem related to the launcher but to the server or the client, I invite you to recreate your issue here: https://github.com/SkyrimTogether/issues-game

Have fun !
