### ISSUE TITLE
Harbor stuck on integrity check

### ISSUE THREAD

**Issue by erathia65** [SkyrimTogether/issues-launcher#19]
## Description

Installed harbor and everything was working fine, connected to my docker server and again, everything working fine, quit the game, and harbor, then re-lauched it, and now harbor is stuck on "integrity check"
No access to the drive are being reported to the task manager

## Steps to reproduce

No idea

## Reproduction rate

Each time launching harbor

## Your environment

* Launcher version: latest at time

* Game edition (choose on which edition do you have problems):
      (both)
    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):

    * Windows 10 x64 pro

## Evidence (optional)

![image](https://user-images.githubusercontent.com/3441742/57974200-d3714200-79b4-11e9-847c-d3d005d430a9.png)

PS: tried reinstalling harbor, selecting oldrim, and no luck

**Comment by UnknownEvil** [comment]
They say you just have to wait

**Comment by WopsS** [comment]
We have a problem with our infrastructure, not a problem with the launcher. Please wait a little bit until we fix this.

**Comment by WopsS** [comment]
Should be fixed now.

**Comment by rosmax3911** [comment]
I’m still having this problem.

**Comment by fein33** [comment]
i'm still having this proplem.
