### ISSUE TITLE
Clicking the register button on the launcher brings to skyrim-together.com instead of oreo.skyrim-together.com

### ISSUE THREAD

**Issue by xNicklaj** [SkyrimTogether/issues-launcher#2]
## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Click on the register button

## Reproduction rate

Every time I clicked on the button

## Expected result

This should redirect to oreo.skyrim-together.com

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system:
     Windows 10 Pro 64 Bit

## Evidence (optional)

Show us what happen.

**Comment by WopsS** [comment]
Thanks for the report! It should be fixed in [v1.0.1](https://github.com/SkyrimTogether/issues-launcher/releases/tag/v1.0.1).
