### ISSUE TITLE
Harbor wont install the setup

### ISSUE THREAD

**Issue by Askense** [SkyrimTogether/issues-launcher#20]
## Description

Harbor keeps saying the installation cant complete when i deleted all the files so i could reinstall it.

## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Connect login.
3. Fail to login.

## Reproduction rate

How many times can you reproduce it?

## Expected result

Describe your expected result.

## Your environment

* Launcher version:

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
    * Windows 7 x32
    * Windows 7 x64
    * Windows 10 x32
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

## Final checks for the reporter

- [ ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ ] I made sure that I have applied the template for my bug report

**Comment by Pokang** [comment]
It seems you have not uninstalled Harbor well, please try and remove it correctly, look for remaining files etc. Let me know if you're still having the issue afterwards.

**Comment by WopsS** [comment]
Get the new version of Harbor, the new one doesn't require you to login.
