### ISSUE TITLE
Avast compatibility error

### ISSUE THREAD

**Issue by megadeth116** [SkyrimTogether/issues-launcher#21]
## Description

While having avast turned on on standard settings:
-You can't install the launcher
-You can't open up the launcher
-You can't open up the game
bacause avast is thinking the files are dangerous and puts the into quarantine
(specifically: "Harbor 1.0.5" installer, "Harbor.exe" launcher and "st_loader_r.exe")

## Steps to reproduce

How to reproduce this issue:

Start the launcher/launcher installer/click on the play button in the launcher

## Reproduction rate

100% while the avast shield is on and 0% when it's off (you can even connect to the setup server if you installed everything correctly with avast being shut down for this time)

## Expected result

Files not being set to quarantine/being deleted

## Your environment

* Launcher version: 1.0.5

* Game edition: 
    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition
       (both)

* Operating system (choose one):
 
    * Windows 7 x64

## Final checks for the reporter

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by Pokang** [comment]
Our launcher and mod trigger a lot of false positives as of right now, since we haven't signed the app to Microsoft yet, please try disabling your antivirus if you want to test the mod, there is no other way right now.
