### ISSUE TITLE
another option to the "right control button " Please!

### ISSUE THREAD

**Issue by neomvll** [SkyrimTogether/issues-launcher#22]
## Description

Just another button to open the "connect tab"
## Additional context

I have a good notebook for games and I dont have a "control button", so I cant connect !!!

EDIT: "control button" I mean "right ctrl button"

**Comment by ReeZey** [comment]
do you have a button to spare?

**Comment by neomvll** [comment]
> do you have a button to spare?

ty for answer, but I dont know what you mean with "button to spare". But the "control button" I said is the "right ctrl button" at keyboard. Sry about my bad complaint.
Anyway, I'm using other usb keyboard only for press right ctrl button hahaha.

**Comment by ReeZey** [comment]
The thing i meant with a spare button is that you can setup a AHK key script for "acting" like you are pressing RCTRL when you press another button example dot/period

**Comment by neomvll** [comment]
Ok, I just forgeted about AHK, now its solved. Thanks a lot! I'm using Rshift to rctrl.
If anyone need it:
`RShift::
Send {RCtrl down}{RCtrl up}
return`
