### ISSUE TITLE
Linux server binary?

### ISSUE THREAD

**Issue by mvlabat** [SkyrimTogether/issues-launcher#24]
As I understand there's only Windows server binary available. Can we expect one for Linux? I'm looking forward to run this on my dedicated server, it would be extremely awesome.

Thank you for you tremendous work on this!

**Comment by ananace** [comment]
The Windows binary actually came second, we released a Linux docker image before that.

If you missed it, it's currently available on;
https://hub.docker.com/r/titledphoques/st-game-server

**Comment by Pokang** [comment]
Quick correction, the new docker link is available here: https://hub.docker.com/r/tiltedphoques/st-game-server
