### ISSUE TITLE
Harbor crashes after installation and executable is gone

### ISSUE THREAD

**Issue by HarambePraiser** [SkyrimTogether/issues-launcher#27]
## Description

I downloaded and installed Harbor, clicked install for the standard edition of Skyrim.
Harbor proceeded to download and crashed

After this, the Harbor executable is nowhere to be found.
![harborbug](https://user-images.githubusercontent.com/49728740/58048050-0993fa80-7b4a-11e9-8144-1b168a2e3c7e.PNG)

When the game starts from normal launcher, the only difference is the ST logo, instead
of the standard one.

## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Start download
3. Download
4. Finish downloading
5. Crash

## Reproduction rate

Fucking always

## Expected result

Results: Harbor executable - gone, Skyrim logo in menu - looking cool

## Your environment

* Launcher version:
Harbor 1.0.5

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim

* Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

I just wanted to tell you guys, that I really appreciate your dedication to this mod.
Keep up the good work <3

## Final checks for the reporter

- [yes] I have browsed through the other issues and confirmed that this issue has not been reported already
- [yes] I made sure that I have applied the template for my bug report

**Comment by Neusor** [comment]
It could be your antivirus flagging the program, and excluding it. 

I suggest checking your antivirus for flagged items.

**Comment by Pokang** [comment]
Definitely an antivirus program, an exe does not delete itself! Please try and disabe your antivirus softwares temporarily, that will fix it.
