### ISSUE TITLE
No access to registration

### ISSUE THREAD

**Issue by mrfaner** [SkyrimTogether/issues-launcher#28]
## Description
Does not go beyond the login window.
When you click on the login disconnect.
When you click on the registration, it transfers to the site https://oreo.skyrim-together.com
where error 404 page not found.
My friend went well and did not throw in the login window.

## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Search the game folder.
3. forced forwarding in login window.
4. register

## Reproduction rate

All time

## Expected result

Opportunity to enter the game

## Your environment

Launcher version:1.0.5
The Elder Scrolls V: Skyrim Special Edition
Windows 10 x64

## Ev
![2](https://user-images.githubusercontent.com/50905383/58158209-a6f24a00-7c82-11e9-9f00-883f4573aa0a.png)

## Final checks for the reporter

- [ +] I have browsed through the other issues and confirmed that this issue has not been reported already
- [+ ] I made sure that I have applied the template for my bug report

**Comment by rxality** [comment]
Please read: https://www.reddit.com/r/SkyrimTogether/comments/bq2jwk/may_2019_report/

**Comment by mrfaner** [comment]
> Please read: https://www.reddit.com/r/SkyrimTogether/comments/bq2jwk/may_2019_report/

I did not really understand what I should focus on

**Comment by rxality** [comment]
Basically, the website is under development but you can access a 'Nightly Build' (which is basically a test build) which does not require an account. Accounts are disabled during website development. You can play this 'Nightly Build' by downloading/updating the latest version of Harbor (1.05).

**Comment by mrfaner** [comment]
> В основном, веб-сайт находится в стадии разработки, но вы можете получить доступ к "ночной сборке" (которая в основном является тестовой сборкой), которая не требует учетной записи. Учетные записи отключаются во время разработки веб-сайта. Вы можете играть в эту "Nightly Build", загрузив/обновив последнюю версию Harbor (1.05).

Version 1.0.5 is loaded, but it still throws to the login window when the game folder is selected. My friend everything went perfectly.

**Comment by mrfaner** [comment]
why close?

**Comment by Pokang** [comment]
The answer to your problem has been given, you don't need to login for nightly builds.
Please try reinstalling the launcher.

**Comment by mrfaner** [comment]
> The answer to your problem has been given, you don't need to login for nightly builds.
> Please try reinstalling the launcher.

I have reinstalled 6 times already(

**Comment by Pokang** [comment]
Can you please record what you're trying to do and upload it somewhere because I'm not sure what's your issue anymore.

**Comment by mrfaner** [comment]
step by step
![1](https://user-images.githubusercontent.com/50905383/58160534-56312000-7c87-11e9-8494-04a728d6a03f.png)
I press browse
![2](https://user-images.githubusercontent.com/50905383/58160571-65b06900-7c87-11e9-996b-1614d3f2da70.png)
chose the game folder.
![3](https://user-images.githubusercontent.com/50905383/58160597-73fe8500-7c87-11e9-91f2-1de35a1f51e9.png)
press install.
![4](https://user-images.githubusercontent.com/50905383/58160623-8082dd80-7c87-11e9-8f5f-fdcf92207c26.png)
login authorization
when i press button register throw into site  https://oreo.skyrim-together.com
where after captcha error 404 page not found.

**Comment by mrfaner** [comment]
> Can you please record what you're trying to do and upload it somewhere because I'm not sure what's your issue anymore.

step by step
![1](https://user-images.githubusercontent.com/50905383/58160534-56312000-7c87-11e9-8494-04a728d6a03f.png)
I press browse
![2](https://user-images.githubusercontent.com/50905383/58160571-65b06900-7c87-11e9-996b-1614d3f2da70.png)
chose the game folder.
![3](https://user-images.githubusercontent.com/50905383/58160597-73fe8500-7c87-11e9-91f2-1de35a1f51e9.png)
press install.
![4](https://user-images.githubusercontent.com/50905383/58160623-8082dd80-7c87-11e9-8f5f-fdcf92207c26.png)
login authorization
when i press button register throw into site  https://oreo.skyrim-together.com
where after captcha error 404 page not found.

**Comment by Pokang** [comment]
Do you have Steam running in the background and did you launch Harbor as administrator?

**Comment by mrfaner** [comment]
> Do you have Steam running in the background and did you launch Harbor as administrator?

Yes, Harbor launch as administrator. Steam launched too

**Comment by mrfaner** [comment]
If Steam turns off and starts the launcher, the error repeats.

**Comment by Pokang** [comment]
Steam has to run in order to launch Skyrim Together. I'm not sure where that's coming from then, the launcher should never redirect you to the login screen.
@WopsS Can you help this guy out?

**Comment by mrfaner** [comment]
I tried as with the disabled Steam and with the included.

**Comment by Pokang** [comment]
Also, are you sure you're using the right version on the launcher? I see you have Skyrim SE selected and you're looking into a Skyrim non-SE folder, please change the version accordingly if you haven't.

**Comment by mrfaner** [comment]
> Also, are you sure you're using the right version on the launcher? I see you have Skyrim SE selected and you're looking into a Skyrim non-SE folder, please change the version accordingly if you haven't.

this is definitely a special version

**Comment by Pokang** [comment]
And I'm telling you it's definitely not. The folder should be named "Skyrim Special Edition" and not "The Elder Scrolls V Skyrim". 
So either you're using the wrong version which is a 2 clicks fix, either you're using a cracked version that I can't provide support for.

**Comment by mrfaner** [comment]
This is exactly the error associated with the launcher. I installed everything exactly on another computer and it all worked.
Run the same installer.
Seen no luck (
![Безымянный](https://user-images.githubusercontent.com/50905383/58162391-c42b1680-7c8a-11e9-913a-a635b47ddc44.png)

**Comment by Pokang** [comment]
Then that confirms me the latter option, which is that you're using a cracked version of Skyrim. I should have known from the start since you're not using the default Steam folder. 
Have a nice day.
