### ISSUE TITLE
Moving harbor/launcher makes it shake and grow

### ISSUE THREAD

**Issue by extract** [SkyrimTogether/issues-launcher#29]
## Description

When moving the launcher from the default position the launcher will start to grow towards top left corner. Once it reaches that point it'll start expanding down and right instead of leaving screen. It does not stop when it reaches all borders, but continues to grow and then can get bigger than screen. (ref. 1)

Sometimes this spits out this error when trying to shut it down (ref. 2)

## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Move window
(3. Close the window) for potential to get error.

## Reproduction rate

100% moving the window.
The error I get while closing the harbor maybe 10%-30% of the time I get the error while closing it

## Expected result

The window should not resize. 
I do not expect it to give me an error on closing the launcher.

## Your environment

* Launcher version: 1.0.5.0

* Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

Ref. 1:
![ezgif-2-9b2cd12887ca](https://user-images.githubusercontent.com/4999714/58353297-6b1bd800-7e6e-11e9-8b36-a5e5097ada28.gif)

Ref. 2: 
![image](https://user-images.githubusercontent.com/4999714/58352220-3bb79c00-7e6b-11e9-83bd-47919f0bea8b.png)

## Final checks for the reporter

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by BenakaR** [comment]
Does it happen for other applications or just Harbor?
Because it doesn't look like the problem with Harbor, or it may be. But better check for others.

**Comment by Pokang** [comment]
I'm unable to reproduce this at all. 
I'm gonna take a wild guess and say it comes from your Windows and system rather than Harbor in itself.
Do you have an unusual resolution by any chance?

**Comment by extract** [comment]
This only happens for Harbor which is interesting, I thought maybe it's due to one of my programs like flux or AquaSnap but I turned off both and it still happens every time for me.
I'm running on 1080p 144Hz screen, but my friend who also runs same screen does not have the problem.
I'll ask another person who I think has the same issue and come back with results. 
I know at least one on discord said it also happened to them, but I don't have proof for that.

**Comment by Pokang** [comment]
I see, that's rather interesting yeah. Try turning off AquaSnap then restarting maybe? That's the number one suspect for me.

The only piece of code we have in the launcher that could be related is the one that forces a 16:9 ratio when resized, but I doubt it's related since you're not resizing the window as far as I can tell.

**Comment by extract** [comment]
The other person who I thought had the same issue was unable to reproduce it.
Tried restarting without AquaSnap and still causes the problem.

I guess until someone else can reproduce this reliably we can consider this closed? 
We can blame my system for now.

**Comment by Pokang** [comment]
Alright, don't hesitate to reopen the issue if you can reproduce it. 
That said, we have a launcher rework coming up which could potentially fix the issue if it's on our side, even though I doubt it. 
Thank you for your report.
