### ISSUE TITLE
Game closed when my friend near me skyrim version.

### ISSUE THREAD

**Issue by canarion** [SkyrimTogether/issues-launcher#37]
## Description

The game closed when my friend its near me , in skyrim version.

## Reproduction rate

How many times can you reproduce it?
10

## Expected result
all time closed
Describe your expected result.
all time closed
## Your environment

* Launcher version:
Skyrim
* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim legendary edition

* Operating system (choose one):
 * Windows 10 x64
 
post: my friend have diferent version he play in skyrim especial edition i dont know dat its possible the problem,

**Comment by Daymonz** [comment]
Me too

**Comment by RainbowCookie32** [comment]
This should go in the game's issue tracker then. https://github.com/SkyrimTogether/issues-game/issues
As far as I can tell, this is for issues with the launcher itself
