### ISSUE TITLE
"This version is not supported" Error

### ISSUE THREAD

**Issue by VirusRenamon** [SkyrimTogether/issues-launcher#39]
## Description

 Cant get past Launcher, had both 1.5.73 and 1.5.80 SSE versions, same outcome.
 ## Steps to reproduce
 
 How to reproduce this issue:
 
    1. Click Play on Harbor. 
 
 ## Reproduction rate
 
 Every single time
 ## Expected result
 
 Skyrim SSE to launch.
 ## Your environment
 
     * Launcher version: 1.0.6

     * Game edition (choose on which edition do you have problems):
      
      * The Elder Scrolls V: Skyrim Special Edition

      * Operating system (choose one):
       
       * Windows 10 x64 Home Edition

 
 ## Evidence (optional)
 
 ![image](https://i.imgur.com/UomUObj.jpg)
 ## Final checks for the reporter
 
     * [X ] I have browsed through the other issues and confirmed that this issue has not been reported already
 
     * [X ] I made sure that I have applied the template for my bug report

**Comment by VirusRenamon** [comment]
Fixed it, needed a new binkw64.dll file for it to work.

I have no clue how this happened as it was a fresh install.

**Comment by M00NGIANT** [comment]
This is still very much an issue. Myself and my friend are experiencing the same problem, and your solution did not work.

**Comment by Pokang** [comment]
@M00NGIANT Could you provide a screenshot of the launcher with the error and of the game installation folder please? I'll be glad to help you out.

**Comment by I-Info** [comment]
@Pokang I have the same problems. 
![image](https://user-images.githubusercontent.com/49438478/89994053-2e7a0d80-dcba-11ea-8775-55f9a87c2d8f.png)
--------- 
I try to use another "binkw64.dll" ,but it is no use.
-----
![image](https://user-images.githubusercontent.com/49438478/89994414-ac3e1900-dcba-11ea-9761-15b81a324313.png)

**Comment by Dison3** [comment]
You need this: https://www.nexusmods.com/skyrimspecialedition/mods/57618?tab=files

**Comment by montzadam** [comment]
Same issue occured.

@Dison3 navigation to patching solved this problem with fresh newly bought Skyrim SE.

**Comment by ScottishOne** [comment]
@Dison3 when I go to use this I select the file path for Skyrim SE right? Just when I do it I get the following error saying "System.Exception: Can't patch file, it doesn't match the expected format". Where is it exactly that i need to put it to? Or am I just being thick
![patch note](https://user-images.githubusercontent.com/98031781/150140495-c27f5878-04a6-4171-9216-05178e054ddb.PNG)
?
