### ISSUE TITLE
Insaller seems to install a trojan

### ISSUE THREAD

**Issue by Awesomeman204** [SkyrimTogether/issues-launcher#41]
This is less of a bug report and more a severe problem

Ran and Installed to my regular Skyrim folder and then I was immediately notified of this:
![ApplicationFrameHost_2Htwrdjq33](https://user-images.githubusercontent.com/52341578/60380086-994e9200-9a82-11e9-8b63-6655b403dd0f.png)

**Comment by gabriezim** [comment]
Hello, this problem was already solved, here is a url for the page that explains this one, but basically is the windows defender blocking the skyrim together loader.
https://www.reddit.com/r/SkyrimTogether/comments/cgdrda/java_script_error_while_launching_skyrim_together/

**Comment by Neusor** [comment]
This is also an duplicate reported issue.

https://github.com/SkyrimTogether/issues-launcher/issues/42
