### ISSUE TITLE
Installer installs multiple trojans

### ISSUE THREAD

**Issue by Bradog21** [SkyrimTogether/issues-launcher#42]
When I installed then ran this file, it started multiple Occamy.C Trojans.
![Trojan list edited](https://user-images.githubusercontent.com/52388008/60403923-f7ee3b80-9b68-11e9-9566-09052c1369e6.png)

**Comment by cikeZ00** [comment]
Those are all false positives.
Its most likely due to the exe file being unsigned.

**Comment by Bradog21** [comment]
I doubt they were... Just now I got an alert of someone trying to log into my google account... luckily it blocked them, but from my research on this type of trojan, it is possible that the attacker was able to get my password.

**Comment by Neusor** [comment]
What are the affected items?

It's moist likely a false positive, this happens since ST is unsigned and injects code into another service (skyrim) anti virus programs don't like that and flag it.

https://www.reddit.com/r/SkyrimTogether/comments/c6uyf8/just_installed_the_most_recent_nightly_build_and/

**Comment by Pokang** [comment]
I can confirm that it is indeed a false positive triggered by our st_loader.exe that injects code into Skyrim, which is seen as malicious by Windows Defender. 
The logging into your google account has nothing to do with us, but please change your password and use a password manager like LastPass that will make you safer.

**Comment by dshadowwolf** [comment]
As of 13-NOV-2020 Windows Defender is detecting st_loader.exe as being a trojan., Seeing this past report I will flag this as a false positive, but felt a notification might be nice to give in case others start screaming.
