### ISSUE TITLE
Javascript Error upon launching Skyrim Together (Skyrim/Non-SE)

### ISSUE THREAD

**Issue by AR019** [SkyrimTogether/issues-launcher#43]
After performing a clean install of Harbor, installing Skyrim Together for Skyrim (Non-SE), and launching - A java script error appears and the Harbor launcher hangs on "Launching". Once closed out of Harbor and relaunching it, it requires me to Install again or update Skyrim Together again. The process repeats even after trying the following: 
- Running as Administrator
- Running with window maximized

Was really looking forward to playing.. could it be just a simple issue?

![Capture](https://user-images.githubusercontent.com/25833808/60632678-017bdb80-9dd5-11e9-94d8-630802e23a8d.PNG)

**Comment by Pokang** [comment]
Please Disable Windows Defender.

It's a false positive.

We haven't signed Harbor yet with a Windows certificate, which means that Windows Defender will not trust its functionality from the get-go. Some of these functionality include torrenting to retrieve the latest mod files and DLL injection to enable our mod in Skyrim. Our plan is to get it signed once we have a stable version of Harbor.

Usually this means that Windows is trying to protect you from installing unknown software that could potentially harm your computer. As we have no intention to do that, but rather deliver a multiplayer experience in Skyrim, I can ensure you that this is a false positive.
