### ISSUE TITLE
The game does not load with HDT

### ISSUE THREAD

**Issue by GonthorianDX** [SkyrimTogether/issues-launcher#44]
I got myself a mod that enables HDT physics (https://schaken-mods.com/index.php?/file/39-hdt-sse-combined-compatibility-set/) but when that is installed, Harbor refuses to load the game.

I expect there is a conflicting .dll to be the culprit. Please investigate.

**Comment by Ralluswettmor** [comment]
the HDT-SMP mod responsible for the launcher does not start and the hdtSSEFramework.DLL now I do not know why I would also like to know

**Comment by GonthorianDX** [comment]
I am not the author of the mod, I merely use it. It does work without any issues by the way.

**Comment by Ralluswettmor** [comment]
Yes, Harbor it does not work when you have hdt-smp installed It only works if you remove hdtSSEFramework.DLL from your folder Best way to get physics and get to play skyrim and without HDT-SMP just install the physics through XP32 then install the plugin CBBE SMP Config available in the optional files of the mod Caliente's Beautiful Bodies Enhancer  sorry my terrible english

**Comment by GonthorianDX** [comment]
If HDT would be possible in the near future I would greatly appeciate it, thanks

**Comment by Ralluswettmor** [comment]
I would also like to see HDT in the near future

**Comment by yamashi** [comment]
We will eventually look into it, for now we only support vanilla skyrim.
