### ISSUE TITLE
Not Loading SKSE for Skyrim Legendary Edition (Non-SE)

### ISSUE THREAD

**Issue by ajsmith21** [SkyrimTogether/issues-launcher#46]
## Description

Launcher is not loading SKSE for the Old-Rim
SKSE is latest version for the classic build 1.7.3 (All Newer versions are for SE)
I do use Mod Organizer to load my mods, but I have tried it without Mod Organizer and using it with it, it will not load SKSE either way.
All my mods do load when using Mod Organizer so at least I know that part works, just not loading SKSE.
 

## Steps to reproduce

How to reproduce this issue:

1. Load the launcher
2. Select "Skyrim" version from the Game version list (required that you have the Old-Rim)
3. Click Play
4. Does not load SKSE

OR Loading through Mod Organizer:

1. Load Up Mod Organizer
2. Make sure you have the option to load Skyrim Together Harbor through the program
3. Run harbor through Mod Organizer
4. Make sure "Skyrim" is selected as the game version
5. Click Play
6. Does not load SKSE

## Reproduction rate

How many times can you reproduce it?
Every time

## Expected result

To Load SKSE on game start

## Your environment

* Launcher version: 1.0.6

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim

* Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

Is there even a log file or a debug mode for this program? If so, I would very much like to know where, I check the application folder, the Skyrim Folder, the AppData folders, I can not seem to find one. If there is, please tell me where or how to get one. I will gladly post that info.
Other than that, SKSE does not load and I can confirm that when I open a saved game it tells me SKSE is not loaded for all the mods that use it.

## Final checks for the reporter

- [ X] I have browsed through the other issues and confirmed that this issue has not been reported already ( I even checked reddit and searched google)
- [?] I made sure that I have applied the template for my bug report (What?)

PS:
I would really like to know how to get a debug log, thanks.

**Comment by ajsmith21** [comment]
@ Over $10k a month in support and after 6 days no answer to this and no updates since the end of may, that is unacceptable.

**Comment by SteamDosh** [comment]
We don't give support for making SKSE work further than attempting to inject the SKSE dll if found in the root directory.

**Comment by ajsmith21** [comment]
Apparently it is not injecting it! Why did you close this issue?

**Comment by ajsmith21** [comment]
I guess I am just done with this project, you guys are never going anywhere...

**Comment by SteamDosh** [comment]
>Apparently it is not injecting it! 

Your mod organizer is the issue not our mod injecting it - please find a guide and understand why the issue is not working rather than flaming the wrong people and blaming them.
