### ISSUE TITLE
Manually option to select SKSE dll file to be injected...

### ISSUE THREAD

**Issue by Smugger21** [SkyrimTogether/issues-launcher#48]
## Description

Allow an option is some sort of settings panel to show if it found the SKSE dll with some sort of check mark and also displaying the version found, and also allow to manually select the dll file from a file open menu.

## Additional context

I am not sure that needs more context but let me know if you need more info from me on what I am talking about I could mock up some sort of images of what I mean.

**Comment by WopsS** [comment]
Hello,

I don't see a reason to add the option to select a SKSE version because the latest SKSE version works with the latest version of Skyrim, could you please explain why it would be useful?

**Comment by Smugger21** [comment]
It is not injecting the SKSE dll in my game. So having the ability to know whether is did find it or not would help. Or if it didn't allowing us to manually select it as an override. 
No one seems to be listening to me that SKSE for old-rim is not being found since it is not the newer version: 32bit Skyrim SKSE - 1.7.3, SE (64bit) Skyrim SKSE - 2.0.16, they are not the same. So I assume that is why it is not finding it. It would be helpful to show us what was found, and give us the option to select it. I don't have the special edition. 
SKSE and Harbor are both in the Skyrim root directory - So that is not the issue
I have asked many placed if there is some sort of debug log file and people still have not told me anything. I looked everywhere from All associated Harbor directories (including those in AppData) and found nothing. I tired many difference command line options while running in powershell, no actual debug output shown. 

So for you there may not be a reason for this, but for some of us, it would be helpful.

**Comment by WopsS** [comment]
Thanks for explaining. It is really odd that it won't find could you check if you have `skse_1_9_32.dll` in your Skyrim directory? This is the file the mod is trying to load.

**Comment by Smugger21** [comment]
Yup, not sure either dude. That is why I think it would be helpful to have a debug log somehow and also show if it found it. 
![2019-08-12 18_16_09-Window](https://user-images.githubusercontent.com/30848479/62902414-8390e580-bd2d-11e9-98a9-5d6fca571fd5.png)

**Comment by WopsS** [comment]
That is odd, I pushed a build to show an error message when SKSE fail to load, should be available in 10-20 minutes.

**Comment by Smugger21** [comment]
Dude, that is awesome, I don't have a lot of time to try it tonight, but I will do it very soon and let you know the outcome, thank you

**Comment by WopsS** [comment]
No problem :)

**Comment by Smugger21** [comment]
Ummm, am I missing something or is it not showing up on releases here on github?

**Comment by WopsS** [comment]
No, the build I pushed is for the mod itself, not launcher. The mod search for SKSE and load it, try to update the mod through launcher and it should log that error.

**Comment by Smugger21** [comment]
Oh, okay, thanks

**Comment by WopsS** [comment]
No problem.

**Comment by Smugger21** [comment]
I have not tested this but just thought of something, will you be making any sort of config file like the ability to do as I said and manually put the SKSE file or stuff like network ip binding, server size, etc, etc?

**Comment by Smugger21** [comment]
Since I am not sure what harbors actual role is besides mod updates and launcher.

**Comment by Smugger21** [comment]
Is there a SKYUI menu for this, I might be asking stupid questions, have never played it or watched it played

**Comment by WopsS** [comment]
I do not plan to make any sort of changes regarding SKSE loading or server related stuff in launcher. Skyrim Together doesn't have a SKYUI menu.

**Comment by Smugger21** [comment]
Ummmm, sorry to bother you again, not sure if I should post a new issue on this but the launcher is no longer loading Skyrim at all, it will check integrity, download the update then I click on play why it is seeding and it just goes back to re-downloading the mod, it does this every time I click play, I can send you a video if you need of what is going on. :(

**Comment by Smugger21** [comment]
I will post a new issue for you, I had thought about it, might be better to start this issue on a new thread, I will continue this thread only for the SKSE issue

**Comment by Smugger21** [comment]
Okay, so I finally figured out what happened, not sure what changed but now my AV thought st_loader was a virus now too.

But I am able to start up the game, and you say there is supposed to be a log file in the 
`[Skyrim Dir]/logs` folder, what is the log supposed to be called? No new logs are showing up when I launch the game from the launcher, I even tried to create a new game and went through the into, and no new logs ever appeared there.

**Comment by Smugger21** [comment]
So ah, ya, I did more double checking again, Loading the game using the skse_loader will load skse with no problems (as tested by using the console command `getskseversion` and show the skse version). 
But Launching the game from [Either]:
 -The Harbor Launcher 
OR from 
- st_loader 
will not load skse.
The Log file is not showing up anywhere.
Running `getskseversion` shows command not found under both of the last two scenarios.

**Comment by Smugger21** [comment]
I FIXED IT!
Turns our it was my ENB, I used SweetFX,
In order to disable it I had to either rename or remove all these file:

`enbseries {folder]
enbbloom.fx
enbeffect.fx
enbeffectprepass.fx
enbhost.exe
enblocal.ini
enbpalette.bmp
enbraindrops.tga
enbseries.ini
enbsunsprite.fx
enbsunsprite.tga
d3d9.dll
d3d9.fx
injector.ini
`


The easiest way to tell if you have this issue is you might get a launch error popup that says:
- Direct3dcreate9ex could not be located
This did not pop up when I first tried, but after the latest mod update it started showing up. 

So if you back up all that stuff or rename them or delete them, you should now be able to load Skyrim WITH SKSE injected.
Again, the error did not show up before the mod update push, it would just run without SKSE loaded, and then after the update I started getting the error, and if I clicked "OK" it would still load Skyrim but SKSE would not be injected.
After I did the above, I was able to get Skyrim to Load Without Error and ran the command `getskseversion` and it finally showed it.
I tested this through:
- The Harbor Launcher
- st_loader
- Mod Organizer running st_loader
And they all work up to the point that I know the mod is actually loaded and that SKSE is now injected.
The New Log Files are now showing up by the way, I see logs called:
- `cef_debug.log`
- `skyrim_together_[date].log` But this is empty, not sure if it supposed to be...
Now moving on to setting up a server and running some test games with my wife.

Thanks for all the help,
Glad you were able to walk me through this!

I hope this helps some people!
