### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by Sosgrosil** [SkyrimTogether/issues-launcher#52]
## Description

When running the server file added by the harbor launcher I ran into the issue of the server not showing that it was online for instance I only received:
{"date":"2019-08-28 21:11:57,119", "level":"INFO", "event":"server_state", "value":"started", "token":"" }
and was unable to get {"date":"2019-08-28 21:11:57,119", "level":"INFO", "event":"server_state", "value":"online", "port":"10570" }
I have triple checked that I did in fact port forward correctly
I tried connecting regardless of this not being shown to no avail
I have tried connecting with my Sub domain and without it
I have tried with and without the port added to the IP

## Steps to reproduce

How to reproduce this issue:

1. Start the Server file given to you by the Harbor Launcher Installation Process.
2. Wait.
3. Fail to login.

## Reproduction rate

I managed to get this every time I opened up the server file

## Expected result
I expected to be able to log in with my sub domain at the very least but did not get in

## Your environment

* Launcher version:

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
  * Windows 10 x64

## Evidence (optional)

I would have added this but I'm new to code and github so this was unavailable to me, if someone tells me how i can do this I can provide screenshots(with my sub domain and/or IP blacked out of course)

## Final checks for the reporter

- [yes] I have browsed through the other issues and confirmed that this issue has not been reported already
- [Yes] I made sure that I have applied the template for my bug report

**Comment by Smugger21** [comment]
Quick question, have you tried to do this only on a local network? That way you can bypass an issues that may have come up with your router and port forwarding?

And just to double check, you are giving our your Public IP address (not your private local network IP address)?

**Comment by Neusor** [comment]
As of the latest server release which introduced the new Network Library, the ports line will no longer show up when running the server 


"value":"started"

As long as this value shows up, it means that the server has started successfully 

https://cdn.discordapp.com/attachments/559447223130390569/609750069553659905/unknown.png

It's probably your firewall acting up, try the firewall fix in this guide.

https://docs.google.com/document/d/1zQKsZSSwDIe9zOuYRux0_BKXr6ojzXpYFsiYSk-ygxg
