### ISSUE TITLE
Check if user's "address:port" input is valid.

### ISSUE THREAD

**Issue by LnLou** [SkyrimTogether/issues-launcher#54]
## Description

Do a grammar check on address:port to let user know input is incorrect.

## Additional context

For example, user might input `127.0.0.1:[10578]` and fails to connect because of incorrect format. It could be helpful if error message is more informative so that user know the problem is about the input, not on server side.

**Comment by Dragonisser** [comment]
1. Use the template
2. https://github.com/SkyrimTogether/issues-game
