### ISSUE TITLE
harbor register bug

### ISSUE THREAD

**Issue by Walruspie12** [SkyrimTogether/issues-launcher#55]
when my friend launches harbor it want her to open up an account and doesnt want anything from me i can play it instantly but she keeps re-launching it even as administrator but it keeps saying to register and when she clicks on register it takes her to oreo.skyrimtogether.com and says 404 error she re-installed it but its still the same please help

## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Try to register
3. Fail to register

## Reproduction rate

Always

## Expected result

Same shit

## Your environment

* Launcher version: 1.0.6

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
 
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

## Final checks for the reporter

- [ ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ ] I made sure that I have applied the template for my bug report

**Comment by Neusor** [comment]
That's the old launcher, uninstall it and get the new one from here https://github.com/SkyrimTogether/issues-launcher/releases/latest
