### ISSUE TITLE
Hello pliase fix disconnects from the game.

### ISSUE THREAD

**Issue by RedGast4** [SkyrimTogether/issues-launcher#58]
pliase fix disconnects from the game and make a stable connection to the server.

**Comment by RedGast4** [comment]
Created the server on a local network of 300 Mbit / sec. Like there should have been enough, but once my friend joined, he lag every second and not show the animation and perks

**Comment by RedGast4** [comment]
Crashes due to the fact that you did not take into account that this problem was in the animation and perks, and the loading of the landscape with the server and client.

**Comment by RedGast4** [comment]
+ system characteristics 
for example I have 4GB of RAM. And how do you explain to me that it will fly.

**Comment by SteamDosh** [comment]
Follow the template, create a proper issue and put it in the correct repo.
