### ISSUE TITLE
Unable to purchase Items from shop

### ISSUE THREAD

**Issue by ThomasCarr1** [SkyrimTogether/issues-launcher#7]
## Description

When trying to buy an Item, the shop menu comes up but the user is unable to interact with the interface.

## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Load a save game
3. Go to Dragonsreach and speak to the wizard.
4. Ask to purchase items

## Reproduction rate

How many times can you reproduce it?

* Every time

## Expected result

* Should open a UI to purchase items.

## Your environment

* Launcher version:
* Latest

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
    * Windows 10 x64

**Comment by f13rce** [comment]
Hi! Thanks for the report.

Hit TAB/end conversation button to start interacting with the shopkeeper's inventory.

Since this report is a duplicate and are already aware of this, I'll close it right away.
