### ISSUE TITLE
will it ever come to console? me and my bro both love skyrim and would love to play together,but we don't wana buy 2 gaming pcs 

### ISSUE THREAD

**Issue by shemi999** [SkyrimTogether/issues-launcher#77]
## Description

A short description about your feature request.

**Comment by ananace** [comment]
I wouldn't hold out hope.  
Not only is it impossible to do DLL injections on consoles - like how we've implemented the mod currently, the mod would also have to be ported to the PowerPC architecture - as that's the CPU architecture that's used at least by the 360, and we'd also have to get access to a console development kit, as well as Bethesda's code most likely.

It _might_ be possible to do with a modded console and a __whole__ lot of work, but I don't think we're really in any position to do so. Just getting SkyrimSE and FO4 working on PC is work enough. :pensive:
