### ISSUE TITLE
Game Not Found on Harbor launcher.

### ISSUE THREAD

**Issue by Ke3sT** [SkyrimTogether/issues-launcher#8]
## Description

I can't start the game. On the launcher, it says GAME NOT FOUND. I tried installing the Launcher on the Skyrim folder also, and it didnt work.

## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Connect login.
3. GAME NOT FOUND

## Reproduction rate

How many times can you reproduce it?

Anytime

## Expected result

Being able to start the game

* Launcher version: 1.0.3

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim

* Operating system (choose one):
    * Windows 10 x64

**Comment by Pokang** [comment]
Please check this post before writing issues here : https://www.reddit.com/r/SkyrimTogether/comments/ajxkwr/all_known_fixes_for_issues_with_skyrim_together/
Thank you, closing accordingly.

**Comment by Rhinorulz** [comment]
I'd appreciate this issue being re-opened, as I have checked and verified that the regristry keys listed in that post are correct, and that SSE is installed.  Is it possible that Harbor has an issue with detecting the game on another drive?  I know a while back, several skyrim launchers had that issue

**Comment by Pokang** [comment]
@Rhinorulz Could you send a screenshot of your game folder, and then of your launcher please?

**Comment by Joerchi** [comment]
**Game installed in:**
F:\The Elder Scrolls V Skyrim Special Edition 

**Harbor installed in:**
F:\Harbor

**Both registry keys are set:**

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Bethesda Softworks\Skyrim Special Edition]
"Installed Path"="F:\\The Elder Scrolls V Skyrim Special Edition"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 489830]
"InstallLocation"="F:\\The Elder Scrolls V Skyrim Special Edition"

**Result:**

After having launched Harbor, it tells me: "**GAME NOT FOUND**". 
Everytime, I need to manually browse to my F drive and point Harbor manually to the install location. Why? 


![screenshot1](https://user-images.githubusercontent.com/5272745/151657028-c6d56a9f-8dd9-4b8c-bccc-75a5d4d1f697.png)
![screenshot2](https://user-images.githubusercontent.com/5272745/151657031-387adae2-50fb-4120-84a7-bf7000239a56.png)
![screenshot3](https://user-images.githubusercontent.com/5272745/151657034-9e57e111-703b-4caa-81a9-2fa912d076d6.png)
![screenshot4](https://user-images.githubusercontent.com/5272745/151657043-8faf4da9-5fca-4eeb-a4c4-3ddf6c167f2c.png)
![screenshot5](https://user-images.githubusercontent.com/5272745/151657045-65f5bbd5-c1b4-42f7-ba36-6c66e85ce9aa.png)
